#!/bin/bash
cp .bashrc "${HOME}/.bashrc"
if [ -x "$(command -v apk)" ]; 
    then apk add --no-cache curl ; fi
if [ -x "$(command -v apt-get)" ];
    then {
	if [ -e /etc/os-release ];
		then {
		source /etc/os-release
		if [[ "$TAILS_PRODUCT_NAME" =~ Tails ]];
			git config --global user.name "amnesia"
			git config --global user.email "amnesia@amnesia"
			then exit; fi
		}; fi
        sudo apt-get update
        sudo apt-get install software-properties-common apt-transport-https curl
        curl -sL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
        sudo apt update
        sudo apt install code
        curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
        sudo apt-get install -y nodejs
    }; fi
if [ -x "$(command -v dnf)" ]; 
    then dnf install curl ; fi
if [ -x "$(command -v zypper)" ]; 
    then zypper install curl ; fi
if [ -x "$(command -v pacman)" ]; 
    then {
        cd /tmp
        git clone https://aur.archlinux.org/yay.git
        cd yay
        makepkg -si
        yay -Syu code nodejs npm
    }; fi
if [ -x "$(command -v eopkg)" ];
    then {
        sudo eopkg install vscode nodejs
    }; fi

mkdir "${HOME}/.npm-packages"
npm config set prefix "${HOME}/.npm-packages"
