#!/bin/bash
sshre='.*@(.*):[0-9]*\/?(.*)\/(.*)\.git'
httpre='https?:\/\/(.*)\/(.*)\/(.*).git\/?'
if [[ $1 =~ $sshre ]]; then
	mkdir -p "$HOME"/git/"${BASH_REMATCH[1]}"
	git clone "$1" "$HOME"/git/"${BASH_REMATCH[1]}"/"${BASH_REMATCH[2]}"
fi
if [[ $1 =~ $httpre ]]; then
	mkdir -p "$HOME"/git/"${BASH_REMATCH[1]}"
	git clone "$1" "$HOME"/git/"${BASH_REMATCH[1]}"/"${BASH_REMATCH[2]}"
fi
