#!/usr/bin/env bash

url="$1"
base="$HOME/git"

if ! norm=$(git ls-remote --get-url "$url" 2>/dev/null); then
  echo "Invalid Git repository URL"
  return 1
fi

norm="${norm#*://}"
norm="${norm#*@}"
norm="${norm/:/\/}"

host="${norm%%/*}"
path="${norm#*/}"
path="${path%.git}"

dest="$base/$host/$path"

mkdir -p "$(dirname "$dest")"
git clone "$url" "$dest"
