#!/bin/bash

find $HOME -name ".git" -type d | while read -r folder; do
	cd ${folder%/.git} || continue
	status=$(git status | grep -c "Changes not staged for commit:")
	if [ $status -gt 0 ]; then
		git checkout -b EmergencyCheckout
		git add -A
		git commit -m "Emergency Commit!"
		git push --force
	fi
done
