#!/bin/bash
dir=$(pwd)
find "$HOME/git" -name ".git" -type d | while read -r folder; do
  cd "${folder%/.git}" || continue
  echo -e "\033[1;34m$(pwd | sed "s%$HOME/git/%%g")\033[0m"
  git pull
done
cd "${dir}" || return
