#!/bin/bash
dir=$(pwd)
for folder in $(find "${HOME}/git" -maxdepth 3 -mindepth 3 -type d | sort); do
    cd "$folder" || exit
    echo -e "\033[0;34m$(pwd)\033[0m"
    git pull
done
cd "$dir" || exit
