#!/usr/bin/env bash
set -e

tmp=$(mktemp)
curl -s https://raw.githubusercontent.com/greflm13/baseline-python/main/new.py -o "$tmp"

exec 3</dev/tty
exec 4>/dev/tty

python3 "$tmp" <&3 >&4 2>&4

rm "$tmp"